# Generated by Django 4.1.7 on 2023-04-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_remove_plan_endvalidaity_remove_plan_startvalidaity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='end_date_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
