# Generated by Django 4.1.7 on 2023-04-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_paypal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='package',
            new_name='plan',
        ),
        migrations.AddField(
            model_name='plan',
            name='unlimited',
            field=models.BooleanField(default=False, verbose_name='غير محدودة'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الباقة'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(verbose_name='سعر الباقة'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='validaity',
            field=models.CharField(max_length=100, verbose_name='دورة الباقة (30 يوم)'),
        ),
    ]
