# Generated by Django 4.1.7 on 2023-04-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0006_rename_package_subscription_plan_plan_unlimited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='videos_per_months',
            field=models.IntegerField(default=0),
        ),
    ]
