# Generated by Django 4.1.7 on 2023-04-13 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pay', '0007_subscription_videos_per_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='videoTemplates',
        ),
        migrations.AddField(
            model_name='features',
            name='template1',
            field=models.BooleanField(default=True, verbose_name='النموذج الأول'),
        ),
        migrations.AddField(
            model_name='features',
            name='template2',
            field=models.BooleanField(default=False, verbose_name='نموذج فيديو مع لوجو'),
        ),
        migrations.AddField(
            model_name='features',
            name='template3',
            field=models.BooleanField(default=False, verbose_name='نموذج تقييم'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
