# Generated by Django 4.1.7 on 2023-04-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0011_alter_features_watermark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='features',
            new_name='Feature',
        ),
    ]
