# Generated by Django 4.1.7 on 2023-04-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0012_rename_features_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='videos_per_months',
            field=models.IntegerField(default=0),
        ),
    ]
