# Generated by Django 4.1.7 on 2023-05-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0014_remove_feature_numbervideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='video_imgs_template',
            field=models.BooleanField(default=True, verbose_name='نموذج صور وفيديوهات'),
        ),
    ]
