# Generated by Django 4.1.7 on 2023-03-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bottom_text',
        ),
        migrations.RemoveField(
            model_name='project',
            name='top_text',
        ),
    ]
