# Generated by Django 4.1.7 on 2023-04-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_project_bottom_text_remove_project_top_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.DeleteModel(
            name='ImageList',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
